@Controller_Based_APIs_HostAddress = http://localhost:5165


@productId = 2779ee47-10b0-4bd7-8342-404006aa1392
@JobId = 0dd4bcf4-98af-4b69-b8d5-57b254872987

### Options 
OPTIONS {{Controller_Based_APIs_HostAddress}}/api/products

### 
HEAD {{Controller_Based_APIs_HostAddress}}/api/products/{{productId}}
###
GET  {{Controller_Based_APIs_HostAddress}}/api/products/{{productId}}

###
GET  {{Controller_Based_APIs_HostAddress}}/api/products/{{productId}}?includeReviews=true
###
GET {{Controller_Based_APIs_HostAddress}}/api/products?page=1&pageSize=100

###
POST {{Controller_Based_APIs_HostAddress}}/api/products
Content-Type: application/json
{
  "name":"saass",
  "price": 1.99
}

###
PUT {{Controller_Based_APIs_HostAddress}}/api/products/{{productId}}
Content-Type: application/json

{
    "name": "chocolate bar",
    "price": 4.50
}

###
PATCH  {{Controller_Based_APIs_HostAddress}}/api/products/{{productId}} 
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "path": "/price",
    "value": 35.99
  },
]

### DELETE
DELETE  {{Controller_Based_APIs_HostAddress}}/api/products/{{productId}}

  
###
POST {{Controller_Based_APIs_HostAddress}}/api/products/process
##

###
GET {{Controller_Based_APIs_HostAddress}}/api/products/status/{{JobId}}

